### ISSUE TITLE
Löschfunktion für mehrere Projekte

### ISSUE THREAD

**Issue by PanteraLX** [PanteraLX/webtrack#5]
geht noch nicht

**Comment by taarist** [comment]
Habs im edit.js hinzugefügt aber funktioniert noch nicht

**Comment by taarist** [comment]
mit Checkboxen arbeiten vor der ID?

**Comment by PanteraLX** [comment]
Ich denke, das lassen wir sein...
Einzelnes löschen sollte reichen
