### ISSUE TITLE
Detailansicht des Projektes

### ISSUE THREAD

**Issue by taarist** [PanteraLX/webtrack#8]
Die einzelnen Projekte in der Übersicht sollten als Hyperlink dargestellt werden, damit beim Klick eine Detailansicht geöffnet wird. Dort sollt ev. in Tabellenform die einzelnen Arbeiten/Phasen des Projektes mit aktuellem Status ersichtlich sein.

**Comment by PanteraLX** [comment]
Sollte erledigt sein
